// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2zMq6H8ATDeaxIVQSH0YBcXOqwwmIcY',
    appId: '1:1017686811958:web:6e1aecbd62897467d03f97',
    messagingSenderId: '1017686811958',
    projectId: 'shabu-umami-db',
    authDomain: 'shabu-umami-db.firebaseapp.com',
    storageBucket: 'shabu-umami-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4aIABigyD6NPdVMA_pTPUlonGReV9d8c',
    appId: '1:1017686811958:android:62d3356b5224cbd0d03f97',
    messagingSenderId: '1017686811958',
    projectId: 'shabu-umami-db',
    storageBucket: 'shabu-umami-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5OGKEMkdV4-4E8Th169RhkkrfNfJW0Z0',
    appId: '1:1017686811958:ios:933af000d3c92d21d03f97',
    messagingSenderId: '1017686811958',
    projectId: 'shabu-umami-db',
    storageBucket: 'shabu-umami-db.firebasestorage.app',
    iosBundleId: 'com.example.shabuUmami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5OGKEMkdV4-4E8Th169RhkkrfNfJW0Z0',
    appId: '1:1017686811958:ios:933af000d3c92d21d03f97',
    messagingSenderId: '1017686811958',
    projectId: 'shabu-umami-db',
    storageBucket: 'shabu-umami-db.firebasestorage.app',
    iosBundleId: 'com.example.shabuUmami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV2zMq6H8ATDeaxIVQSH0YBcXOqwwmIcY',
    appId: '1:1017686811958:web:cf9ba0be02e2b616d03f97',
    messagingSenderId: '1017686811958',
    projectId: 'shabu-umami-db',
    authDomain: 'shabu-umami-db.firebaseapp.com',
    storageBucket: 'shabu-umami-db.firebasestorage.app',
  );
}
